export const paths = {
  home: '/',
  login: 'login',
  signup: 'signup',
  talentRegister: 'talentRegister',
  solution: 'solution',
  aboutUs: 'about-us',
  faq: 'faq',
  testimonials: 'testimonials',
  pricing: 'pricing',
  features: 'features',
  blog: 'https://mysalesplat.com/blog/',
  facebook: 'https://facebook.com/Salesplat',
  twitter: 'https://x.com/SalesPlat',
  instagram: 'https://www.instagram.com/salesplat/',
  linkedIn: 'https://www.linkedin.com/company/salesplat/posts/?feedView=all',
  youtube: 'https://www.youtube.com/@Incubate_by_SalesPlat',
  privacyPolicy: 'privacy-policy',
  termsConditions: 'terms-and-conditions',
}
