name: Deploy Frontend Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies and Build
      run: |
        yarn install
        NODE_OPTIONS='--max-old-space-size=4096' yarn build

    - name: Deploy to Server
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        
        eval "$(ssh-agent -s)"
        echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null

        
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "sudo systemctl stop nginx"

        
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "sudo rm -rf $SERVER_PATH/*"
        scp -o StrictHostKeyChecking=no -r dist/* $SERVER_USER@$SERVER_HOST:$SERVER_PATH

        # Restart Nginx
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "sudo systemctl start nginx"
